pool:
  vmImage: 'macos-latest'

steps:

- script: ./build.sh --configuration=$(configuration) --outputDir="$(Build.ArtifactStagingDirectory)"
  displayName: "🧁 Cake build"

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesdirectory)'
    Contents: '*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'artifacts'
    publishLocation: 'Container'